In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("iris.csv")

array = df.to_numpy()
print("Data Types:")
print(array.dtype)
print("\nShape:")
print(array.shape)


Data Types:
object

Shape:
(150, 6)


In [7]:
mean = np.mean(numerical_cols, axis=0) # Mean
std_dev = np.std(numerical_cols, axis=0) # Standard Deviation

standardized_array = (numerical_cols - mean) / std_dev # Standardize the numerical features using broadcasting

print("Standardized Array:")
print(standardized_array)

Standardized Array:
           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -1.720542      -0.900681      1.032057      -1.341272     -1.312977
1   -1.697448      -1.143017     -0.124958      -1.341272     -1.312977
2   -1.674353      -1.385353      0.337848      -1.398138     -1.312977
3   -1.651258      -1.506521      0.106445      -1.284407     -1.312977
4   -1.628164      -1.021849      1.263460      -1.341272     -1.312977
..        ...            ...           ...            ...           ...
145  1.628164       1.038005     -0.124958       0.819624      1.447956
146  1.651258       0.553333     -1.281972       0.705893      0.922064
147  1.674353       0.795669     -0.124958       0.819624      1.053537
148  1.697448       0.432165      0.800654       0.933356      1.447956
149  1.720542       0.068662     -0.124958       0.762759      0.790591

[150 rows x 5 columns]


In [6]:
correlation_matrix = np.corrcoef(numerical_cols, rowvar=False)# # Compute the correlation matrix using NumPy's corrcoef function
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[ 1.          0.71667627 -0.39772881  0.88274732  0.89975858]
 [ 0.71667627  1.         -0.10936925  0.87175416  0.81795363]
 [-0.39772881 -0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.88274732  0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.89975858  0.81795363 -0.35654409  0.9627571   1.        ]]


In [9]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [10]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset
iris = load_iris()
X, y = iris.data, iris.target

# Step 2: Split the dataset into features (X) and labels (y)
# Note: No need for feature scaling for k-NN, but we'll still split the data for consistency
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Normalize the features (standardization)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 5: Implement k-NN algorithm
def knn(X_train, y_train, X_test, k):
    # Compute pairwise distances between training and testing samples
    distances = np.sqrt(np.sum((X_train[:, np.newaxis] - X_test) ** 2, axis=2))
    
    # Find k nearest neighbors for each testing sample
    nearest_neighbors = np.argsort(distances, axis=0)[:k]
    
    # Predict labels based on the majority vote of the nearest neighbors
    y_pred = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=0, arr=y_train[nearest_neighbors]) # This step will be caculated by Chatgpt.
    
    return y_pred

def evaluate(y_true, y_pred):                           # Step 6: Evaluate the model
    accuracy = accuracy_score(y_true, y_pred)
    return accuracy

k = 3 # Set the value of k for k-NN

y_pred = knn(X_train_scaled, y_train, X_test_scaled, k) # Apply k-NN algorithm

accuracy = evaluate(y_test, y_pred)                     # Evaluate the model
print("Accuracy:", accuracy)


Accuracy: 1.0


In [15]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
x

mean_value=np.mean(x,axis=0)
mean_value


array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [16]:
median_value=np.median(x,axis=0)
median_value

array([5.8 , 3.  , 4.35, 1.3 ])

In [17]:
std_value=np.std(x,axis=0)
std_value

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [18]:
var_value=np.var(x,axis=0)
var_value

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [19]:
np.min(X,axis=0)

array([4.3, 2. , 1. , 0.1])

In [20]:
np.max(X,axis=0)

array([7.9, 4.4, 6.9, 2.5])